---
- name: Install and configure WordPress and MySQL
  hosts: web_server
  become: true
  vars:
    db_name: mysqldb
    db_user: Pabby
    pass_wd: [Desrired Password]

  tasks:
    - debug:
        var: db_user

    - debug:
        msg: "Database User Created"
    - debug:
        var: db_user
    - debug:
        msg: "Database Created"
    - debug:
        var: db_user

    - debug:
        msg: "Database User Created"

    - debug:
        var: pass_wd

    - debug:
        msg: "Database Password Created"

    - name: Install Apache web server
      apt:
        name: apache2
        state: present

    - name: Start and enable Apache service
      service:
        name: apache2
        state: started
        enabled: true

    - name: Install PHP and required modules
      apt:
        name:
          - php
          - php-mysql

    - name: Download and extract WordPress
      get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /var/www/html/wordpress.tar.gz

    - name: Extract WordPress archive
      command: tar -xvzf /var/www/html/wordpress.tar.gz -C /var/www/html/

- name: Configure MySQL Database
  hosts: db_server
  become: true
  tasks:
    - name: Install MySQL Server
      apt:
        name: mysql-server
        state: present

    - name: Start and enable MySQL service
      service:
        name: mysql
        state: started
        enabled: true

    - name: Create MySQL Database with name 'accounts'
      mysql_db:
        name: "{{db_name}}"
        state: present

    - name: Create Databse User
      mysql_user:
        name: "{{db_user}}"
        password: "{{pass_wd}}"
        priv: '*.*:ALL'
        state: present
